// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesManagement.Models;

namespace MoviesManagement.Migrations
{
    [DbContext(typeof(MoviesManagementContext))]
    partial class MoviesManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesManagement.Models.MoviesManagement", b =>
                {
                    b.Property<int>("movie_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("movie_date_release")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("movie_language")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("movie_ori_country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("movie_title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("movie_year");

                    b.HasKey("movie_id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
